In [1]:
import numpy as ny

In [2]:
print(ny.arange(2,50,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [3]:
 l1=[]
l2=[]
for i in range (0,5):
    ele=int(input())
    l1.append(ele)
for i in range (0,5):
    ele=int(input())
    l2.append(ele)   
a= ny.array(l1)
b=ny.array(l2)

arr = ny.concatenate((a, b))
print(arr)
c=ny.sort(arr)
print(c)

2
3
5
1
8
4
7
7
6
9
[2 3 5 1 8 4 7 7 6 9]
[1 2 3 4 5 6 7 7 8 9]


In [4]:
a = ny.array([[1,2,3,4,5,6,7,8],[2,3,4,5,6,7,8,9]])
print(a)
print(a.shape)

[[1 2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8 9]]
(2, 8)


this means that the array contains 8 elements and has dimension 2

In [5]:
a=ny.array([1,2,3,4,5,6,7,8,9,10])
b=a.reshape(2,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
a=ny.array([[1,2,6],[3,4,5]])
b=ny.array([[7,8,9],[4,2,7]])
e=ny.vstack((a,b))
f=ny.hstack((a,b))
print(e)
print(f)

[[1 2 6]
 [3 4 5]
 [7 8 9]
 [4 2 7]]
[[1 2 6 7 8 9]
 [3 4 5 4 2 7]]


In [7]:
a=ny.array([1,2,4,6,3,5,7,8,4,9,7,6,5,3,2])
unique,counts=ny.unique(a,return_counts=True)
a=ny.asarray((unique,counts)).T
print(a)

[[1 1]
 [2 2]
 [3 2]
 [4 2]
 [5 2]
 [6 2]
 [7 2]
 [8 1]
 [9 1]]
